package(default_visibility=['//visibility:public'])

cc_library(
  name = 'controller_simple',
  srcs = ['simple.cpp'],
  hdrs = ['simple.h'],
  deps = ['//third_party/unitscpp', 
          '//challenges/elevator:elevator']
)
