package(default_visibility=['//visibility:public'])

cc_library(
  name = 'controller_simple',
  srcs = ['simple.cpp'],
  hdrs = ['simple.h'],
  deps = ['//third_party/unitscpp', '//challenges/pivot:pivot']
)

cc_library(
  name = 'controller_brake',
  srcs = ['disk_brake.cpp'],
  hdrs = ['disk_brake.h'],
  deps = ['//third_party/unitscpp', '//challenges/pivot:pivot']
)
