package(default_visibility=['//visibility:public'])

cc_library(
  name = 'controller_simple',
  srcs = ['simple.cpp'],
  hdrs = ['simple.h'],
  deps = ['//third_party/unitscpp']
)

cc_library(
  name = 'controller_no_friction',
  srcs = ['no_friction.cpp'],
  hdrs = ['no_friction.h'],
  deps = ['//third_party/unitscpp']
)

cc_library(
  name = 'controller_goal',
  srcs = ['goal.cpp'],
  hdrs = ['goal.h'],
  deps = ['//third_party/unitscpp']
)
