package(default_visibility=['//visibility:public'])

cc_library(
  name = 'controller_simple',
  srcs = ['simple.cpp'],
  hdrs = ['simple.h'],
  deps = ['//third_party/unitscpp', '//challenges/turret:turret']
)

cc_library(
  name = 'controller_follow',
  srcs = ['moving_goal.cpp'],
  hdrs = ['moving_goal.h'],
  deps = ['//third_party/unitscpp', '//challenges/turret:turret']
)
